/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DomainModels.TaiKhoan;
import Services.Impl.TaiKhoanServiceImpl;
import Services.TaiKhoanService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author truongmanhquang
 */
public class DoiMatKhauJpanel extends javax.swing.JPanel {

    public String userID;
    private List<TaiKhoan> listTK=new ArrayList<>();
    private TaiKhoanService taiKhoanService=new TaiKhoanServiceImpl();
    /**
     * Creates new form DoiMatKhauJpanel
     */
    public DoiMatKhauJpanel() {
        initComponents();
    }
    
    public DoiMatKhauJpanel(String user) {
        initComponents();
        userID=user;
    }
    
    private boolean checkTrong() {
        if (txtUID.getText().isEmpty()
                ) {
            return false;
        }
        return true;
    }
    
    private boolean checkTrong1() {
        if (txtOldPass.getText().isEmpty()
                ) {
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        txtOldPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        txtCfnPass = new javax.swing.JPasswordField();
        lblUID = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        lblCfnPass = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setText("Nhập mật khẩu cũ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setText("Xác nhận mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel4.setText("Nhập mật khẩu mới");

        btnChangePass.setBackground(new java.awt.Color(255, 204, 204));
        btnChangePass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đổi mật khẩu");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setText("Tài khoản");

        lblUID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUID.setForeground(new java.awt.Color(255, 0, 0));

        lblOldPass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblOldPass.setForeground(new java.awt.Color(255, 0, 0));

        lblCfnPass.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCfnPass.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 618, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCfnPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUID, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(txtOldPass)
                            .addComponent(txtNewPass)
                            .addComponent(txtCfnPass)
                            .addComponent(lblUID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOldPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUID)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOldPass)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCfnPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCfnPass)
                .addGap(28, 28, 28)
                .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        int result=JOptionPane.showConfirmDialog(this, "Xác nhận đổi mật khẩu", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION){
        try {
            String uid=txtUID.getText();
        String oldPass=txtOldPass.getText();
        String newPass=txtNewPass.getText();
        String cfnPass=txtCfnPass.getText();
        TaiKhoan tk=new TaiKhoan(uid, oldPass, newPass, cfnPass);
            taiKhoanService.getOne(uid);
            if(checkTrong() || checkTrong1()){
                if(taiKhoanService.checkLogin(uid, oldPass)){//tk.getMatKhau().equals(oldPass)
                    lblOldPass.setText("");
                    if(newPass.equals(cfnPass)){
                        lblCfnPass.setText("");
                        taiKhoanService.update(tk, uid);
                        JOptionPane.showMessageDialog(this, "Password Change Successfully");
                    }else{
                        lblCfnPass.setText("Confirm Password Does not Match");
                        txtCfnPass.requestFocus();
                    }
                }else{
                    lblOldPass.setText("Invalid Old Password");
                    txtOldPass.requestFocus();
                }
                lblUID.setText("");
            }else{
                lblUID.setText("Invalid User ID");
                txtUID.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        }else{
            return;
        }
    }//GEN-LAST:event_btnChangePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCfnPass;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblUID;
    private javax.swing.JPasswordField txtCfnPass;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables
}
